application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      milo-indexer:
        license: Apache-2.0
        actions:
          hello:
            function: actions/hello/index.js
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug